apiVersion: v1
kind: ConfigMap
metadata:
  name: layotto-runtime-config
data:
  config.json: |
    {
      "servers": [
        {
          "default_log_path": "stdout",
          "default_log_level": "DEBUG",
          "routers": [
            {
              "router_config_name": "actuator_dont_need_router"
            }
          ],
          "listeners": [
            {
              "name": "grpc",
              "address": "0.0.0.0:34904",
              "bind_port": true,
              "filter_chains": [
                {
                  "filters": [
                    {
                      "type": "grpc",
                      "config": {
                        "server_name": "runtime",
                        "grpc_config": {
                          "hellos": {
                            "helloworld": {
                              "type": "helloworld",
                              "hello": "greeting"
                            }
                          },
                          "state": {
                            "state_demo": {
                              "type": "in-memory",
                              "metadata": {
                              }
                            }
                          },
                          "lock": {
                            "lock_demo": {
                              "type": "in-memory",
                              "metadata": {
                              }
                            }
                          },
                          "pub_subs": {
                            "pub_subs_demo": {
                              "type": "in-memory",
                              "metadata": {
                                "consumerID": "1"
                              }
                            }
                          },
                          "sequencer": {
                            "sequencer_demo": {
                              "type": "in-memory",
                              "metadata": {}
                            }
                          },
                          "secret_store": {
                            "secret_demo": {
                              "type": "local.env",
                              "metadata": {
                              }
                            }
                          },
                          "bindings": {
                            "bindings_demo": {
                              "type": "http",
                              "metadata": {
                                "url": "https://mosn.io/layotto"
                              }
                            }
                          },
                          "custom_component": {
                            "helloworld": {
                              "demo": {
                                "type": "in-memory",
                                "metadata": {}
                              }
                            }
                          },
                          "app": {
                            "app_id": "app1",
                            "grpc_callback_port": 9999
                          }
                        }
                      }
                    }
                  ]
                }
              ]
            },
            {
              "name": "actuator",
              "address": "127.0.0.1:34999",
              "bind_port": true,
              "filter_chains": [
                {
                  "filters": [
                    {
                      "type": "proxy",
                      "config": {
                        "downstream_protocol": "Http1",
                        "upstream_protocol": "Http1",
                        "router_config_name": "actuator_dont_need_router"
                      }
                    }
                  ]
                }
              ],
              "stream_filters": [
                {
                  "type": "actuator_filter"
                }
              ]
            }
          ]
        }
      ],
      "tracing": {
        "enable": true,
        "driver": "SOFATracer",
        "config": {
          "generator": "mosntracing",
          "exporter": [
            "stdout"
          ]
        }
      },
      "metrics": {
        "sinks": [
          {
            "type": "prometheus",
            "config": {
              "port": 34903
            }
          }
        ]
      }
    }