# Auto build and release docker image to docker hub when releasing tags
---
name: Release Layotto Image

on:
  create

jobs:
  publish_image:
    name: Release Layotto image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.5
        with:
          submodules: recursive

      - name: Extract Tags name
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: tag_env
        shell: bash
        run: |
          echo "##[set-output name=version;]$(echo ${GITHUB_REF##*/})"
        
      - name: Login to Docker Hub
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Layotto Image
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          make image tag=${{ steps.tag_env.outputs.version }}

      - name: Push Layotto Docker image
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          docker push layotto/layotto:${{ steps.tag_env.outputs.version }}
  