name: Sync with Yuque
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  sync:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      
      - name: Call Sync API
        run: |
          echo ${{ steps.get_commit_id.outputs.commit_id }}
          curl --location --request POST 'http://127.0.0.1:8777/v1/rest/sync' \
            --header 'Content-Type: application/json' \
            --data '{
              "inputs": {
                "yuqueNamespace": "eg6z1a/qpbul9",
                "yuqueSite": "https://mosn-layotto.yuque.com/",
                "yuqueToken":"GMxMZw92ioczAGOCTueGOHSJOo6pr6tGTP3TgXLf",
                "gitRepo": "https://github.com/${{ github.repository }}",
                "gitDocRoot": "/",
                "gitDocToc": "SUMMARY.md",
                "gitBranch": "main"
              }
            }'
